Add Font Awesome local close #69
reviakin/gorkogo55-landing pull request #70
Opened 2019-10-01 21:05 UTC by Nebula223

2019-10-06 15:57 UTC, MaxFlower requested changes
Требуется поправить импорт дополнительного файла стилей.

2019-10-06 15:57 UTC, MaxFlower commented on index.html
> +    <link rel="stylesheet" href="./styles/all.css">
Здесь, как и в нескольких других файлах дублируется подключение  нового `all.css`, однако достаточно сделать один раз импорт этого файла в `style.css`.

Документация:
[Импорт css](https://www.w3schools.com/cssref/pr_import_rule.asp)

2019-10-06 15:57 UTC, MaxFlower commented on index.html
> +      document.addEventListener("DOMContentLoaded", function() {
Хорошо, что удалось почистить код от лишних пробелов, хоть это визуально незаметный для конечного пользователя результат, но очень важно привыкать и иметь привычку иметь чистый, красивый код.

Так как в данном проекте не используется никакой сборщик ()gulp, webpack) это значит каждый пробел увеличивает размер файла, а значит в дальнейшем может стать проблемой.

Чтобы избежать подобных проблем достаточно настроить линтнеры. Можно попробовать настроить их либо здесь или в каком-то еще репозитории.

Дополнительно:
[пакет html lint ](https://www.npmjs.com/package/htmllint)

2019-10-07 07:53 UTC, MaxFlower approved these changes
Approved.

2019-10-07 19:43 UTC, merged

2019-10-07 20:02 UTC, VadimCpp commented
Большое спасибо, @MaxFlower